version: 2
jobs:
  build:
    docker:
      - image: node:8.0
        environment:
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-deps-{ .Branch }-{ checksum "package.json" }
          - v1-deps-{ .Branch }
          - v1-deps
      - run: npm ci
      - save_cache:
        key: v1-deps-{ .Branch }-{ checksum "package.json" }
          paths:
            - ~/.cache
            - ~/.npm
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
