version: 2
jobs:
  build:
    working_directory: ~/income-and-taxes
    docker:
      - image: circleci/node:8.0
      - image: cypress/base:6
    steps:
      - checkout
      - run:
          name: install brew
          command: '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
      - run:
          name: remove node modules
          command: 'sudo rm -rf /usr/local/lib/node_modules'
      - run:
          name: remove npm
          command: 'sudo rm -rf ~/.npm'
      - run:
          name: uninstall node
          command: 'brew uninstall --force node'
      - run:
          name: install node
          command: 'brew install node'
      - run:
          name: install npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm ci
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache
            - ~/.npm
  test:
    docker:
      - image: circleci/node:8.0
      - image: cypress/base:6
    steps:
      - checkout
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: multiple-results
          path: cypress/videos
          path: cypress/screenshots

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
